name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: "Description"

jobs:
  build:
    name: Firebase Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v5

      # Setup Java
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build unsigned release APK
      - name: Build unsigned release
        run: ./gradlew assembleRelease

      # Debug: List APK outputs
      - name: List APK outputs
        run: ls -R sample/build/outputs/apk/release

      # Decode keystore from GitHub secret
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

      # Sign APK with apksigner
      - name: Sign APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out sample/build/outputs/apk/release/sample-release-signed.apk \
            sample/build/outputs/apk/release/sample-release.apk

      # Verify APK signature
      - name: Verify APK signature
        run: |
          echo "Verifying signed APK..."
          $ANDROID_HOME/build-tools/34.0.0/apksigner verify --print-certs sample/build/outputs/apk/release/sample-release-signed.apk

      # Upload signed APK to Firebase App Distribution
      - name: Upload signed APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: sample/build/outputs/apk/release/sample-release-signed.apk
          releaseNotes: ${{ inputs.release_notes }}
